"""Add OCR fields to Note model

Revision ID: 39aaf198ec17
Revises: 4b6b2dee6a93
Create Date: 2025-10-04 17:42:26.211522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39aaf198ec17'
down_revision = '4b6b2dee6a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markdown_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ocr_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('ocr_status')
        batch_op.drop_column('markdown_path')

    # ### end Alembic commands ###
